// Generated by agentic orchestrator | run greenfield-20261002-160423 | node impl_api
package com.example.shortener.error;

/** Domain error carrying the HTTP status it maps to, kept free of web types so the service layer stays portable. */
public class ShortenerException extends RuntimeException {

    private final int status;
    private final String title;

    public ShortenerException(int status, String title, String detail) {
        super(detail);
        this.status = status;
        this.title = title;
    }

    public int status() { return status; }

    public String title() { return title; }

    public static ShortenerException invalid(String detail) {
        return new ShortenerException(400, "Invalid request", detail);
    }

    public static ShortenerException forbidden(String detail) {
        return new ShortenerException(403, "Forbidden", detail);
    }

    public static ShortenerException notFound(String code) {
        return new ShortenerException(404, "Not found", "No short URL with code '" + code + "'");
    }

    public static ShortenerException aliasTaken(String alias) {
        return new ShortenerException(409, "Alias unavailable", "Alias '" + alias + "' is not available");
    }

    public static ShortenerException gone(String code) {
        return new ShortenerException(410, "Gone", "Short URL '" + code + "' was deleted or has expired");
    }

    public static ShortenerException unavailable(String detail) {
        return new ShortenerException(503, "Service unavailable", detail);
    }
}
