// Generated by agentic orchestrator | run greenfield-20261002-160423 | node impl_api
package com.example.shortener.dto;

import java.time.Instant;

public record StatsResponse(String code, long totalClicks, Instant lastAccessedAt) {}
